---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wei.
--- DateTime: 2018/10/25 18:59
---
-- 定义数组
local keys = KEYS;
local args = ARGV;

local product_pre="productId:";
local goods_pre = "goodsId:"
result = {};
result[1]=12;
print(result[1])

--for i, v in ipairs(keys) do
--    print(i .. v)
--    result[]
--end

--for k, v in pairs(args) do
--    print(k .. v)
--end
print(table.getn(result));