---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wei.
--- DateTime: 2018/10/27 9:56
---

require "mobdebug".start()
-- require("mobdebug").start("host-ip", port) --默认值为 "localhost", 8172







