---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wei.
--- DateTime: 2018/10/27 9:56
---
require("transition.StringAndTableTB");
local ta = Common:unserialize("{productId=1,stock=0}");
local ta_str = Common:serialize(ta);
print(ta.productId);

print(ta_str)

if ta.aa == nil then
    print(true);
else
    print(false)
end

